on: 
  push:
    branches:
      - hw

jobs:
  my_testing :
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: Prepare project
      run : |
        sudo apt update -y
        sudo apt install -y cppcheck clang-tidy python3-pip libc6-dbg cmake libgtest-dev
        sudo pip install cpplint

    - name: TESTS + COVERAGE
      run : make test

    - name: LINTER
      run : make check