on: 
  push:
    branches:
      - hw2

jobs:
  my_testing :
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: Prepare project
      run : make prepare

    - name: TESTS + COVERAGE
      run : ./HW2/make test